### ISSUE TITLE
Hardcoded Links

### ISSUE THREAD

**Issue by amcdnl** [sta-szek/gitbook-plugin-githubcontributors#6]
It looks like you hardcoded your project ;)

https://github.com/sta-szek/gitbook-plugin-githubcontributors/blob/master/assets/contributors.js#L35

**Comment by sta-szek** [comment]
Thanks, I will do this today later,.
Eventually you can send PR :)

**Comment by amcdnl** [comment]
Thanks!

**Comment by sta-szek** [comment]
Thanks for reporting. I thought only I am using this plugin :smile:

**Comment by amcdnl** [comment]
Na, its great. Using it on https://swimlane.gitbooks.io/angular2-data-table/content/contributing/credits.html :)

**Comment by sta-szek** [comment]
Oh I see new feature #8

**Comment by sta-szek** [comment]
@amcdnl is the contributors section better now? (after #8 )

**Comment by amcdnl** [comment]
Ya, looks nice ... Idea: Add margin around the user blocks so the grey has padding around each.
